py3:
  extension: ".py"

  version_command:
    command: "python3"
    args:
      - "--version"

  run:
    - "python3"
    - "{source}"

cpp:
  extension: ".cpp"

  version_command:
    command: "g++"
    args:
      - "--version"

  compile:
    - "g++"
    - "{source}"
    - "-o"
    - "{artifact}"

  run:
   - "{artifact}"