py3:
  name: "Python 3"

  default_run_limits:
    wall_time_s: 9
    memory_kb: 102400
    max_processes: 100

  extension: ".py"

  version_command:
    command: "python3"
    args:
      - "--version"

  allowed_build_flags: []

  allowed_run_flags:
    - "-B"
    - "-O"

  run:
    - "python3"
    - "{run_flags}"
    - "{source}"

c:
  name: "C"

  default_run_limits:
    wall_time_s: 9
    memory_kb: 102400
    max_processes: 100

  extension: ".c"

  version_command:
    command: "gcc"
    args:
      - "--version"

  allowed_build_flags:
    - "-O0"
    - "-O1"
    - "-O2"
    - "-O3"
    - "-Wall"
    - "-Wextra"
    - "-std=*"

  allowed_run_flags: []

  compile:
    - "gcc"
    - "{build_flags}"
    - "{source}"
    - "-o"
    - "{artifact}"

  run:
    - "{artifact}"

cpp:
  name: "C++"

  default_run_limits:
    wall_time_s: 9
    memory_kb: 102400
    max_processes: 100

  extension: ".cpp"

  version_command:
    command: "g++"
    args:
      - "--version"

  allowed_build_flags:
    - "-O0"
    - "-O1"
    - "-O2"
    - "-O3"
    - "-Wall"
    - "-Wextra"
    - "-std=*"

  allowed_run_flags: []

  compile:
    - "g++"
    - "{build_flags}"
    - "{source}"
    - "-o"
    - "{artifact}"

  run:
    - "{artifact}"

java:
  name: "Java"

  default_run_limits:
    wall_time_s: 9
    memory_kb: 102400
    max_processes: 100

  extension: ".java"

  version_command:
    command: "javac"
    args:
      - "-version"

  allowed_build_flags: []

  allowed_run_flags: []

  compile:
    - "javac"
    - "{build_flags}"
    - "{source}"

  run:
    - "java"
    - "{run_flags}"
    - "-cp"
    - "{workspace}"
    - "Main"

bash:
  name: "Bash"

  default_run_limits:
    wall_time_s: 9
    memory_kb: 102400
    max_processes: 100

  extension: ".sh"

  version_command:
    command: "bash"
    args:
      - "--version"

  allowed_build_flags: []

  allowed_run_flags: []

  run:
    - "bash"
    - "{source}"

js:
  name: "JavaScript (Node)"

  default_run_limits:
    wall_time_s: 9
    memory_kb: 102400
    max_processes: 100

  extension: ".js"

  version_command:
    command: "node"
    args:
      - "--version"

  allowed_build_flags: []

  allowed_run_flags: []

  run:
    - "node"
    - "{run_flags}"
    - "{source}"

verilog:
  name: "Verilog"

  default_run_limits:
    wall_time_s: 9
    memory_kb: 102400
    max_processes: 100

  extension: ".v"

  version_command:
    command: "iverilog"
    args:
      - "-V"

  allowed_build_flags:
    - "-Wall"

  allowed_run_flags: []

  compile:
    - "iverilog"
    - "{build_flags}"
    - "{source}"
    - "-o"
    - "{artifact}"

  run:
    - "vvp"
    - "{artifact}"